language: java
install: gradle wrapper --gradle-version 4.8
sudo: false # faster builds

jdk:
  - oraclejdk8
services:
  - docker
before_install:
  - docker run -p 6379:6379 -d --name redis redis:3.0.7-alpine
  - chmod +x gradlew

script:
  - ./gradlew clean build
  - ./gradlew pitest
