language: java
install:
  - gradle wrapper --gradle-version 4.8
  - ./gradlew assemble -x signArchives
sudo: required
jdk:
  - oraclejdk8
branches:
  only:
  - master
services:
  - docker
before_install:
  - docker run -p 6379:6379 -d --name redis redis:3.0.7-alpine
  - chmod +x gradlew
script:
  - "./gradlew check"
after_success:
  - "./deploy.sh"