language: java
install: gradle wrapper --gradle-version 4.8
sudo: false # faster builds

jdk:
  - oraclejdk8
  
before_install:
 - chmod +x gradlew  

script:
  - ./gradlew clean build
  - ./gradlew pitest
