language: java
install: gradle wrapper --gradle-version 4.8
sudo: required
jdk:
  - oraclejdk8
branches:
  only:
  - master
services:
  - docker
before_install:
  - docker run -p 6379:6379 -d --name redis redis:3.0.7-alpine
  - docker run -d --hostname rabbit --name rabbit -p 8080:15672 -p 5672:5672 rabbitmq:3-management
  - chmod +x gradlew
script:
  - "./gradlew clean build"
  - "./gradlew pitest"
