theme: jekyll-theme-architect

title: Event.Store
description: [A simple and fast EventStore that support multiple persistence and notification providers]

github:
  node_url: https://github.com/thiagobustamante/node-eventstore/
  java_url: https://github.com/biharck/eventstore