version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/redis

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: docker run -p 6379:6379 -d --name redis circleci/redis
      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle pitest

  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: ./deploy.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy